language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install -y --no-install-recommends software-properties-common
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudo apt-get upgrade

script:
  - cmake CMakeLists.txt
  - make