language: cpp

os:
  - linux

compiler:
  - gcc
  - clang

install:
  - sudo apt-get install software-properties-common
  - sudo add-apt-repository ppa:george-edison55/cmake-3.x
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends cmake

script:
  - cmake CMakeLists.txt