#ifndef CPPW67RENDER_OPENUTILS_H
#define CPPW67RENDER_OPENUTILS_H

#include <GLFW/glfw3.h>

typedef unsigned char short255;

#define DRAW_TYPE_QUADS GL_QUADS
#define DRAW_TYPE_LINES GL_LINES

#endif //CPPW67RENDER_OPENUTILS_H
